# fly.toml file generated for parchapp on 2023-04-25T20:33:09-05:00

app = "parchapp"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bog"
processes = []

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
