# Define la versión de build de Netlify
[build]
  command = "docker build . -t my_docker_image"
  publish = "my_docker_image:latest"

# Define las configuraciones de la aplicación
[dev]
  command = "docker run -p 8000:8000 -e DJANGO_SETTINGS_MODULE=myproject.settings.dev my_docker_image"

[build.environment]
  # Define las variables de entorno
  DB_HOST = "localhost"
  DB_NAME = "my_db"
  DB_USER = "my_user"
  DB_PASSWORD = "my_password"
